/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ilegra0227' at '10/04/17 14:48' with Gradle 2.14.1
 *
 * @author ilegra0227, @date 10/04/17 14:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
